name: Check Artifact

on: 
  [push]
  
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: download md artifact
      uses: actions/upload-artifact@v2
      with:
        name: mdArtifact
        path: temp.md
