name: Check Artifact

on: 
   [push]

  
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
#     - run: touch temp.md && echo "hi" > temp.md
#     - name: upload md artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: mdArtifact
#         path: temp.md
    - name: Checkout repo
      uses: actions/checkout@v2
    - run: 
         | 
         cd mdFiles
         ls > ../result.md
    - name: Upload md artifact
      uses: actions/upload-artifact@v2
      with:
         name: mdArtifact
         path: results.md
      
