name: Check Artifact

on: 
   [push]

  
jobs:
  job_1:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.16.2
      options: --entrypoint=sh
    steps:
#     - run: touch temp.md && echo "hi" > temp.md
#     - name: upload md artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: mdArtifact
#         path: temp.md
    - name: Checkout repo
      uses: actions/checkout@v2
    - run: 
         | 
         cd mdFiles
         for file in $(find . -name "*.md")
         do
         cat $file >> ../output/resultData.md
         echo -e "\n" >> ../output/resultData.md
         done
         ls > ../output/result.md
         cd ..
    - name: Convert Markdown To docx
      run: |
          pandoc -f markdown -t docx --number-sections --file-scope  output/result.md -o output/result.docx

    - name: Upload md artifact
      uses: actions/upload-artifact@v2
      with:
         name: output
         path: output
      
