name: Check Artifact

on: 
   push:
      paths: 'README.md"

  
jobs:
  job_1:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.16.2
      options: --entrypoint=sh
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - run: 
         | 
         rm -rf output
         mkdir output
         for file in $(find . -name "*.md")
         do
         cat $file > output/resultData.md
         echo -e "\n" >> output/resultData.md
         done
         ls > output/result.md
         
    - name: Convert Markdown To docx
      run: |
          pandoc -f markdown -t docx --number-sections --file-scope  output/result.md -o output/result.docx
          pandoc -f markdown -t docx --number-sections --file-scope  output/resultData.md -o output/resultData.docx
          
    - name: Upload md artifact
      uses: actions/upload-artifact@v2
      with:
         name: output
         path: output
  job_2:
    name: job2
    needs: job_1
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - run: mkdir docs
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
       name: output
       path: docs
    - run: |
          git config --global user.email "sudarshan16rms@gmail.com"
          git config --global user.name "Sudarshan Suryaprakash"
          git add .
          git commit -m "add artifacts to output"
          git push
    - uses: geekyeggo/delete-artifact@v1
      with:
         name: output
#     - run: |
#          mv /home/runner/work/artifacts/artifacts/output ./output
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
