name: Check Artifact

on: 
   push:
      branches:
         "develop"
      paths: 'README.md'
   workflow_dispatch:
   

  
jobs:
  Generate_PR_Docx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create singular md file
      run: 
         | 
         rm -rf docs
         mkdir docs
         for file in $(find . -name "*.md")
         do
         cat $file >> docs/resultData.md
         echo -e "\n" >> docs/resultData.md
         done
         
    - name: Install Pandoc
      run: sudo apt install pandoc
    
    - name: Convert Markdown To docx
      run: |
        pandoc -f markdown -t docx --number-sections --file-scope  docs/resultData.md -o docs/resultData.docx
        rm docs/resultData.md
        
    - name: Push changes
      run: |
        git config --global user.email "<>"
        git config --global user.name "Docx Pusher"
        git add .
        git commit -m "Add output"
        git push
        
    - uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
